spring.application.name=sound-rate
server.port=8080
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.profiles.default=local

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
app.cors.allowed-origins=http://localhost:4200,https://soundrate-05gm.onrender.com

jwt.issuer=sound-rate-api
jwt.secret=${JWT_SECRET}

cloudinary.url=${CLOUDINARY_URL}
spring.sendgrid.api-key=${SENDGRID_API_KEY}
app.sendgrid.from-email=contatosoundrate@gmail.com
